services:
  mongodb:
    image: mongo:latest
    container_name: task-forge-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: task-forge-mongodb-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: task-forge-mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-forge-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI:
        mongodb://admin:password@mongdb:27017/task-forge?authSource=admin
    depends_on:
      - mongodb

volumes:
  mongo_data: